version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - premier-app:/usr/src/app
      - /usr/src/app/node_modules
    container_name: premier-league
    restart: always
    ports:
      - 8000:8000
      - 9229:9229
    command: npm run dev
    depends_on:
      - mongo
    networks:
      - premier
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27027:27027"
    volumes:
      - database_mongo:/data/database_mongo
    networks:
      - premier

volumes:
  premier-app:
  database_mongo:

networks:
  premier
